// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzybprpgsxuowcdlpams.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6eWJwcnBnc3h1b3djZGxwYW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTA5MTIsImV4cCI6MjA2NjQyNjkxMn0.4h4-JbdFjkd9feyfUwbEJ2Pg0HKnoAfC2usvunhxUeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);